import {
    pgTable,
    uuid,
    varchar,
    text,
    numeric,
    integer,
    timestamp,
    pgEnum,
    index,
    check,
    foreignKey,
} from "drizzle-orm/pg-core";

import { sql } from "drizzle-orm";

import { users } from "./users";
import { ShareStatus } from "../../enums/share.enum";

export const shareStatusEnum = pgEnum(
    "share_status",
    [
        ShareStatus.STARTED,
        ShareStatus.IN_PROGRESS,
        ShareStatus.CLOSED,
    ],
);

export const shares = pgTable(
    "shares",
    {
        id: uuid("id")
            .defaultRandom()
            .primaryKey(),

        /**
         * Admin that created the share.
         */
        createdBy: uuid("created_by")
            .notNull(),

        /**
         * Name displayed to users.
         */
        name: varchar("name", {
            length: 150,
        }).notNull(),

        /**
         * Share logo/image URL.
         *
         * Generated by Cloudinary after
         * an admin uploads the logo.
         */
        logo: varchar("logo", {
            length: 500,
        }),

        /**
         * Cloudinary public ID for the logo.
         *
         * Used when replacing or deleting
         * the uploaded logo.
         */
        logoPublicId: varchar("logo_public_id", {
            length: 255,
        }),

        /**
         * Full share description.
         */
        description: text("description"),

        /**
         * Daily return percentage.
         *
         * Example:
         * 16 = 16% daily return.
         */
        dailyReturnPercentage: numeric(
            "daily_return_percentage",
            {
                precision: 8,
                scale: 4,
            },
        ).notNull(),

        /**
         * Share cycle duration in days.
         *
         * Example:
         * 200 days.
         */
        cycleDays: integer(
            "cycle_days",
        ).notNull(),

        /**
         * Current share lifecycle.
         */
        status: shareStatusEnum(
            "status",
        )
            .default(
                ShareStatus.STARTED,
            )
            .notNull(),

        /**
         * When the share became available.
         */
        startedAt: timestamp(
            "started_at",
        )
            .defaultNow()
            .notNull(),

        /**
         * When the share was closed.
         */
        closedAt: timestamp(
            "closed_at",
        ),

        createdAt: timestamp(
            "created_at",
        )
            .defaultNow()
            .notNull(),

        updatedAt: timestamp(
            "updated_at",
        )
            .defaultNow()
            .$onUpdate(() => new Date())
            .notNull(),
    },

    (table) => [
        foreignKey({
            columns: [table.createdBy],
            foreignColumns: [users.id],
            name: "shares_created_by_fk",
        }).onDelete("restrict"),

        index(
            "shares_created_by_idx",
        ).on(table.createdBy),

        index(
            "shares_status_idx",
        ).on(table.status),

        index(
            "shares_created_at_idx",
        ).on(table.createdAt),

        check(
            "shares_daily_return_percentage_positive",
            sql`${table.dailyReturnPercentage} > 0`,
        ),

        check(
            "shares_cycle_days_positive",
            sql`${table.cycleDays} > 0`,
        ),
    ],
);